version: '3'

services:
  flask-backend:
    container_name: flask-backend
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/server
    depends_on:
      - db
    restart: always

  
  react:
    container_name: react
    build: ./frontend
    volumes:
      - './frontend:/app'
    ports:
      - 3000:3000

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
    ports:
      - '5432:5432'
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data