version: '3.6'

services:
  flask-backend:
    build: ./backend
    
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://admin:password@db/samples
    
    networks:
      - default
    ports:
      - 5000:5000

    restart: always
    
  db:
  environment:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: password
    POSTGRES_DB: samples

  image: postgres:14.1-alpine

  networks:
    - default
  ports:
    - 5405:5432
  restart: always
  volumes:
    - ./postgres-data:/var/lib/postgresql/data