version: '3'

services:
  flask-backend:
    container_name: flask-backend
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/server
    restart: always

  
  react:
    container_name: react
    build: ./frontend
    volumes:
      - './frontend:/app'
    ports:
      - 3000:3000