FROM ubuntu 

RUN apt-get update && apt-get install -y software-properties-common gcc && \
    add-apt-repository -y ppa:deadsnakes/ppa

RUN apt-get update && apt-get install -y python3.6 python3-distutils python3-pip python3-apt

RUN apt-get -y install libpq-dev gcc \
    && pip install psycopg2

COPY . /server
WORKDIR /server

RUN apt-get update

RUN pip install --no-cache-dir -r requirements.txt
ENV FLASK_DEBUG=1
ENV FLASK_ENV=development

EXPOSE 5000

CMD ["python3", "app.py"]